MultiIndex Tutorial  
https://www.datacamp.com/community/tutorials/pandas-multi-index

Datcamp Tutorial on hierarchical indexing  
https://github.com/datacamp/community-hierarchical-indices/blob/master/hierarchical_indices_multiple_groupbys_and_pandas.ipynb

In [2]:
import pandas as pd
import time
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import sys
import datetime
import os
import seaborn as sns
import math as mth
import pickle
import re
import nltk
import spacy
import sklearn

import tika
from tika import parser

import bokeh
from bokeh.plotting import *
from bokeh.io import output_notebook
from bokeh.models import Toggle, BoxAnnotation, CustomJS, HoverTool

output_notebook()

from sklearn.manifold import TSNE

#import plotly
#from plotly.graph_objs import *
#import plotly.plotly as py
#import plotly.tools as tls
#from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

#import plotly.offline as offline
#offline.init_notebook_mode(connected=False)
#init_notebook_mode(connected=False)

#import cufflinks as cf
#import colorlover as cl

#Plotly API Information:(username='asl4af', api_key='7ut55tktdt')
#plotly.tools.set_credentials_file(username='Zanderl',api_key='2NRGAPpIAjvFhmUZ8dQF')

#Make all charts public and set a global theme
#cf.set_config_file(world_readable=True,theme='white',offline=True)

#tls.embed('https://plot.ly/~cufflinks/8')

sns.set_style("white")

%matplotlib inline

from IPython.display import display

from IPython.display import HTML

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [23]:
%%time

df1 = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                   encoding='utf-8',sheetname=0,parse_dates=True)

df2 = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                    encoding='utf-8',sheetname=1,parse_dates=True)

df9 = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                    encoding='utf-8',sheetname=9,parse_dates=True)

C:\Users\zanderl\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel.py:351: UserWarning: The 'parse_dates=True' keyword of read_excel was provided without an 'index_col' keyword value.
  warn("The 'parse_dates=True' keyword of read_excel was provided"

Wall time: 9.24 s

In [17]:
def GetData():
    
    df_number = range(0,8,1)
    df_name = []
    
    for i in df_number:
        df_name.append(i)
    
    df_list = []
    
    for val in df_name:
        
        df = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                    encoding='utf-8',sheetname=int(val),parse_dates=True,index_col=2)
        
        df_list.append(df+str(val))
    return df_list
        
        #print(df_name)

In [18]:
%%time
sc_data = GetData()
df1 = pd.concat(sc_data,join='inner')

Wall time: 21.2 s

In [24]:
df1.shape
df1.head()
df1.describe(include='all')
df1.info()
pd.isnull(df1).sum()

(577, 6)

,Date,Company,Smart Connection,Connection Type,Headline,Market Impact
0,"Jan. 1, 1982",M&T Bank Corporation,NaN,Person starts any role by company,Robert Wilmers begins tenure as a Board Member...,Low
1,"Jan. 1, 1983",M&T Bank Corporation,NaN,Person starts any role by company,Brent Baird begins tenure as a Board Member at...,Low
2,"Jan. 1, 1983",M&T Bank Corporation,NaN,Person starts a specified role by company,Robert Wilmers begins tenure as President at M...,Low
3,"Jan. 1, 1991",M&T Bank Corporation,NaN,Person starts any role by company,C. Bontempo begins tenure as a Board Member at...,Low
4,"Dec. 14, 1993",M&T Bank Corporation,NaN,News,"M&T Bank Corporation announces 506,930 share r...",Low

,Date,Company,Smart Connection,Connection Type,Headline,Market Impact
count,577,577,222,577,577,577
unique,423,4,3,21,528,3
top,"Dec. 1, 2017",M&T Bank Corporation,F.N.B. Corporation is a peer of M&T Bank Corpo...,Earnings releases,Tranche Update on M&T Bank Corporation (NYSE:M...,Low
freq,7,355,78,300,25,251

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 6 columns):
Date                577 non-null object
Company             577 non-null object
Smart Connection    222 non-null object
Connection Type     577 non-null object
Headline            577 non-null object
Market Impact       577 non-null object
dtypes: object(6)
memory usage: 27.1+ KB

Date                  0
Company               0
Smart Connection    355
Connection Type       0
Headline              0
Market Impact         0
dtype: int64

In [25]:
df1.set_index(['Company','Market Impact'])
#df1[df1['Market Impact'] == 'High']

                                             Date  \
Company              Market Impact
M&T Bank Corporation Low            Jan.  1, 1982
                     Low            Jan.  1, 1983
                     Low            Jan.  1, 1983
                     Low            Jan.  1, 1991
                     Low            Dec. 14, 1993
                     Low            Jan.  1, 1994
                     Low            Nov. 29, 1995
                     Low            Jan.  1, 1996
                     Low            Feb. 19, 1997
                     Low            May. 20, 1998
                     Low            Oct.  1, 1998
                     Low            Jan.  1, 1999
                     High           Apr. 20, 1999
F.N.B. Corporation   Medium         May. 14, 1999
M&T Bank Corporation Low            May. 14, 1999
                     High           Jul. 12, 1999
F.N.B. Corporation   Medium         Jul. 15, 1999
M&T Bank Corporation High           Oct.  8, 1999
F.N.B. Corporation   Medium         Oct. 19, 1999
M&T Bank Corporation Low            Nov. 24, 1999
                     Low            Jan.  1, 2000
                     High           Jan. 10, 2000
F.N.B. Corporation   Medium         Jan. 18, 2000
BB&T Corporation     Medium         Apr. 11, 2000
F.N.B. Corporation   Medium         Apr. 13, 2000
M&T Bank Corporation High           Apr. 18, 2000
                     High           Jul. 11, 2000
BB&T Corporation     Medium         Jul. 12, 2000
F.N.B. Corporation   Medium         Jul. 17, 2000
M&T Bank Corporation High           Oct. 11, 2000
...                                           ...
                     Low            Dec. 20, 2017
                     Low            Dec. 20, 2017
                     Low            Dec. 20, 2017
                     Low            Dec. 20, 2017
                     Low            Dec. 20, 2017
                     Low            Dec. 20, 2017
BlackRock            Medium         Jan. 12, 2018
BB&T Corporation     Medium         Jan. 18, 2018
M&T Bank Corporation High           Jan. 18, 2018
                     Low            Jan. 18, 2018
                     Low            Jan. 18, 2018
                     High           Jan. 18, 2018
                     Low            Jan. 18, 2018
F.N.B. Corporation   Medium         Jan. 23, 2018
M&T Bank Corporation Low            Feb. 21, 2018
                     Low            Feb. 21, 2018
                     Low            Feb. 21, 2018
BlackRock            Medium         Apr. 12, 2018
M&T Bank Corporation Low            Apr. 16, 2018
                     High           Apr. 16, 2018
                     Low            Apr. 16, 2018
                     Low            Apr. 16, 2018
                     High           Apr. 17, 2018
                     Low            Apr. 17, 2018
BB&T Corporation     Medium         Apr. 19, 2018
F.N.B. Corporation   Medium         Apr. 24, 2018
BlackRock            Medium         Jul. 13, 2018
M&T Bank Corporation High           Jul. 18, 2018
F.N.B. Corporation   Medium         Jul. 19, 2018
BB&T Corporation     Medium         Jul. 19, 2018

                                                                     Smart Connection  \
Company              Market Impact
M&T Bank Corporation Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     High                                                         NaN
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
M&T Bank Corporation Low                                                          NaN
                     High                                                         NaN
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
M&T Bank Corporation High                                                         NaN
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
M&T Bank Corporation Low                                                          NaN
                     Low                                                          NaN
                     High                                                         NaN
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
BB&T Corporation     Medium         BB&T Corporation is a peer of M&T Bank Corpora...
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
M&T Bank Corporation High                                                         NaN
                     High                                                         NaN
BB&T Corporation     Medium         BB&T Corporation is a peer of M&T Bank Corpora...
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
M&T Bank Corporation High                                                         NaN
...                                                                               ...
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
BlackRock            Medium               BlackRock is a peer of M&T Bank Corporation
BB&T Corporation     Medium         BB&T Corporation is a peer of M&T Bank Corpora...
M&T Bank Corporation High                                                         NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     High                                                         NaN
                     Low                                                          NaN
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
M&T Bank Corporation Low                                                          NaN
                     Low                                                          NaN
                     Low                                                          NaN
BlackRock            Medium               BlackRock is a peer of M&T Bank Corporation
M&T Bank Corporation Low                                                          NaN
                     High                                                         NaN
                     Low                                                          NaN
                     Low                                                          NaN
                     High                                                         NaN
                     Low                                                          NaN
BB&T Corporation     Medium         BB&T Corporation is a peer of M&T Bank Corpora...
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
BlackRock            Medium               BlackRock is a peer of M&T Bank Corporation
M&T Bank Corporation High                                                         NaN
F.N.B. Corporation   Medium         F.N.B. Corporation is a peer of M&T Bank Corpo...
BB&T Corporation     Medium         BB&T Corporation is a peer of M&T Bank Corpora...

                                                              Connection Type  \
Company              Market Impact
M&T Bank Corporation Low                    Person starts any role by company
                     Low                    Person starts any role by company
                     Low            Person starts a specified role by company
                     Low                    Person starts any role by company
                     Low                                                 News
                     Low                    Person starts any role by company
                     Low                                                 News
                     Low                    Person starts any role by company
                     Low                                                 News
                     Low                                                 News
                     Low                                                 News
                     Low                    Person starts any role by company
                     High                                   Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
M&T Bank Corporation Low                                                 News
                     High                                   Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
M&T Bank Corporation High                                   Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
M&T Bank Corporation Low                                                 News
                     Low                    Person starts any role by company
                     High                                   Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
BB&T Corporation     Medium                                 Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
M&T Bank Corporation High                                   Earnings releases
                     High                                   Earnings releases
BB&T Corporation     Medium                                 Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
M&T Bank Corporation High                                   Earnings releases
...                                                                       ...
                     Low                    Person starts any role by company
                     Low                    Person starts any role by company
                     Low            Person starts a specified role by company
                     Low                    Person starts any role by company
                     Low            Person starts a specified role by company
                     Low                    Person starts any role by company
BlackRock            Medium                                 Earnings releases
BB&T Corporation     Medium                                 Earnings releases
M&T Bank Corporation High                                   Earnings releases
                     Low                               Impairments/Write Offs
                     Low                               Buyback Tranche Update
                     High                  Corporate Guidance - New/Confirmed
                     Low                                   Preferred Dividend
F.N.B. Corporation   Medium                                 Earnings releases
M&T Bank Corporation Low                    Buyback Transaction Announcements
                     Low                    Buyback Transaction Announcements
                     Low                                Dividend Affirmations
BlackRock            Medium                                 Earnings releases
M&T Bank Corporation Low                               Impairments/Write Offs
                     High                                   Earnings releases
                     Low                               Buyback Tranche Update
                     Low                               Buyback Tranche Update
                     High                              Annual General Meeting
                     Low                                   Preferred Dividend
BB&T Corporation     Medium                                 Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
BlackRock            Medium                                 Earnings releases
M&T Bank Corporation High                                   Earnings releases
F.N.B. Corporation   Medium                                 Earnings releases
BB&T Corporation     Medium                                 Earnings releases

                                                                             Headline
Company              Market Impact
M&T Bank Corporation Low            Robert Wilmers begins tenure as a Board Member...
                     Low            Brent Baird begins tenure as a Board Member at...
                     Low            Robert Wilmers begins tenure as President at M...
                     Low            C. Bontempo begins tenure as a Board Member at...
                     Low            M&T Bank Corporation announces 506,930 share r...
                     Low            Robert Brady begins tenure as a Board Member a...
                     Low            M&T Bank Corporation announces 380,582 share r...
                     Low            Herbert Washington begins tenure as a Board Me...
                     Low            M&T Bank Corporation announces 303,317 share r...
                     Low            M&T Bank Corporation announces additional 155,...
                     Low            M&T Bank Corporation announces additional 200,...
                     Low            Robert Sadler begins tenure as a Board Member ...
                     High             M&T Bank Corporation Earnings Release (Q1 1999)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q1 1999)
M&T Bank Corporation Low            M&T Bank Corporation announces additional 134,...
                     High             M&T Bank Corporation Earnings Release (Q2 1999)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q2 1999)
M&T Bank Corporation High             M&T Bank Corporation Earnings Release (Q3 1999)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q3 1999)
M&T Bank Corporation Low            M&T Bank Corporation announces 190,465 share r...
                     Low            Robert Wilmers begins tenure as Chair at M&T B...
                     High             M&T Bank Corporation Earnings Release (Q4 1999)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q4 1999)
BB&T Corporation     Medium               BB&T Corporation Earnings Release (Q1 2000)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q1 2000)
M&T Bank Corporation High             M&T Bank Corporation Earnings Release (Q1 2000)
                     High             M&T Bank Corporation Earnings Release (Q2 2000)
BB&T Corporation     Medium               BB&T Corporation Earnings Release (Q2 2000)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q2 2000)
M&T Bank Corporation High             M&T Bank Corporation Earnings Release (Q3 2000)
...                                                                               ...
                     Low            Richard Gold begins tenure as a Board Member a...
                     Low            Richard Gold begins tenure as Chief Operating ...
                     Low            René Jones begins tenure as CEO at M&T Bank Co...
                     Low            René Jones begins tenure as Chair at M&T Bank ...
                     Low            Richard Gold begins tenure as President at M&T...
                     Low            René Jones begins tenure as a Board Member at ...
BlackRock            Medium                      BlackRock Earnings Release (Q4 2017)
BB&T Corporation     Medium               BB&T Corporation Earnings Release (Q4 2017)
M&T Bank Corporation High             M&T Bank Corporation Earnings Release (Q4 2017)
                     Low            M&T Bank Corporation Reports Consolidated Earn...
                     Low            Tranche Update on M&T Bank Corporation (NYSE:M...
                     High           M&T Bank Corporation Provides Effective Tax Ra...
                     Low            M&T Bank Corporation Declares Quarterly Cash D...
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q4 2017)
M&T Bank Corporation Low              M&T Bank Corporation authorizes a Buyback Plan.
                     Low            M&T Bank Corporation (NYSE:MTB) announces an E...
                     Low            M&T Bank Corporation Declares Quarterly Cash D...
BlackRock            Medium                      BlackRock Earnings Release (Q1 2018)
M&T Bank Corporation Low            M&T Bank Corporation Reports Consolidated Earn...
                     High             M&T Bank Corporation Earnings Release (Q1 2018)
                     Low            Tranche Update on M&T Bank Corporation (NYSE:M...
                     Low            Tranche Update on M&T Bank Corporation (NYSE:M...
                     High           M&T Bank Corporation, Annual General Meeting, ...
                     Low            M&T Bank Corporation Announces Dividend Declar...
BB&T Corporation     Medium               BB&T Corporation Earnings Release (Q1 2018)
F.N.B. Corporation   Medium             F.N.B. Corporation Earnings Release (Q1 2018)
BlackRock            Medium            BlackRock Estimated Earnings Release (Q2 2018)
M&T Bank Corporation High           M&T Bank Corporation Estimated Earnings Releas...
F.N.B. Corporation   Medium         F.N.B. Corporation Estimated Earnings Release ...
BB&T Corporation     Medium               BB&T Corporation Earnings Release (Q2 2018)

[577 rows x 4 columns]

In [18]:
df1_single_company = pd.DataFrame(df1[df1['Company'] == 'M&T Bank Corporation'])

In [19]:
df1_single_company.head()

,Company,Smart Connection,Connection Type,Headline,Market Impact
Date,,,,,
1982-01-01,M&T Bank Corporation,NaN,Person starts any role by company,Robert Wilmers begins tenure as a Board Member...,Low
1983-01-01,M&T Bank Corporation,NaN,Person starts any role by company,Brent Baird begins tenure as a Board Member at...,Low
1983-01-01,M&T Bank Corporation,NaN,Person starts a specified role by company,Robert Wilmers begins tenure as President at M...,Low
1991-01-01,M&T Bank Corporation,NaN,Person starts any role by company,C. Bontempo begins tenure as a Board Member at...,Low
1993-12-14,M&T Bank Corporation,NaN,News,"M&T Bank Corporation announces 506,930 share r...",Low

In [122]:
df1_co_counts = df1.pivot_table(index=['Company','Connection Type','Market Impact'],aggfunc='count')
df1_co_counts

                                                                                   Date  \
Company              Connection Type                                Market Impact
BB&T Corporation     Earnings releases                              Medium           74
BlackRock            Earnings releases                              Medium           70
F.N.B. Corporation   Earnings releases                              Medium           78
M&T Bank Corporation Annual General Meeting                         High             14
                     Buyback - Change in Plan Terms                 Low               1
                     Buyback Tranche Update                         Low              39
                     Buyback Transaction Announcements              Low              12
                     Corporate Guidance - New/Confirmed             High              6
                     Discontinued Operations/Downsizings            Low              20
                     Dividend Affirmations                          Low              59
                     Dividend Increases                             Medium            6
                     Earnings releases                              High             78
                     Fixed Income Issuance Announcements by Company Low               5
                     Impairments/Write Offs                         Low              22
                     M&A Calls                                      Low               3
                     News                                           Low              16
                     Person ends a specified role by company        Low               7
                     Person ends any role by company                Low               2
                     Person starts a specified role by company      Low              10
                     Person starts any role by company              Low              28
                     Preferred Dividend                             Low              21
                     Regulatory Agency Inquiries                    Low               1
                     Special/Extraordinary Shareholders Meeting     Low               2
                     acquisition_announcements                      Low               3

                                                                                   Headline  \
Company              Connection Type                                Market Impact
BB&T Corporation     Earnings releases                              Medium               74
BlackRock            Earnings releases                              Medium               70
F.N.B. Corporation   Earnings releases                              Medium               78
M&T Bank Corporation Annual General Meeting                         High                 14
                     Buyback - Change in Plan Terms                 Low                   1
                     Buyback Tranche Update                         Low                  39
                     Buyback Transaction Announcements              Low                  12
                     Corporate Guidance - New/Confirmed             High                  6
                     Discontinued Operations/Downsizings            Low                  20
                     Dividend Affirmations                          Low                  59
                     Dividend Increases                             Medium                6
                     Earnings releases                              High                 78
                     Fixed Income Issuance Announcements by Company Low                   5
                     Impairments/Write Offs                         Low                  22
                     M&A Calls                                      Low                   3
                     News                                           Low                  16
                     Person ends a specified role by company        Low                   7
                     Person ends any role by company                Low                   2
                     Person starts a specified role by company      Low                  10
                     Person starts any role by company              Low                  28
                     Preferred Dividend                             Low                  21
                     Regulatory Agency Inquiries                    Low                   1
                     Special/Extraordinary Shareholders Meeting     Low                   2
                     acquisition_announcements                      Low                   3

                                                                                   Smart Connection
Company              Connection Type                                Market Impact
BB&T Corporation     Earnings releases                              Medium                       74
BlackRock            Earnings releases                              Medium                       70
F.N.B. Corporation   Earnings releases                              Medium                       78
M&T Bank Corporation Annual General Meeting                         High                          0
                     Buyback - Change in Plan Terms                 Low                           0
                     Buyback Tranche Update                         Low                           0
                     Buyback Transaction Announcements              Low                           0
                     Corporate Guidance - New/Confirmed             High                          0
                     Discontinued Operations/Downsizings            Low                           0
                     Dividend Affirmations                          Low                           0
                     Dividend Increases                             Medium                        0
                     Earnings releases                              High                          0
                     Fixed Income Issuance Announcements by Company Low                           0
                     Impairments/Write Offs                         Low                           0
                     M&A Calls                                      Low                           0
                     News                                           Low                           0
                     Person ends a specified role by company        Low                           0
                     Person ends any role by company                Low                           0
                     Person starts a specified role by company      Low                           0
                     Person starts any role by company              Low                           0
                     Preferred Dividend                             Low                           0
                     Regulatory Agency Inquiries                    Low                           0
                     Special/Extraordinary Shareholders Meeting     Low                           0
                     acquisition_announcements                      Low                           0

In [123]:
(df1_co_counts / len(df1)*100)

                                                                                        Date  \
Company              Connection Type                                Market Impact
BB&T Corporation     Earnings releases                              Medium         12.824957
BlackRock            Earnings releases                              Medium         12.131716
F.N.B. Corporation   Earnings releases                              Medium         13.518198
M&T Bank Corporation Annual General Meeting                         High            2.426343
                     Buyback - Change in Plan Terms                 Low             0.173310
                     Buyback Tranche Update                         Low             6.759099
                     Buyback Transaction Announcements              Low             2.079723
                     Corporate Guidance - New/Confirmed             High            1.039861
                     Discontinued Operations/Downsizings            Low             3.466205
                     Dividend Affirmations                          Low            10.225303
                     Dividend Increases                             Medium          1.039861
                     Earnings releases                              High           13.518198
                     Fixed Income Issuance Announcements by Company Low             0.866551
                     Impairments/Write Offs                         Low             3.812825
                     M&A Calls                                      Low             0.519931
                     News                                           Low             2.772964
                     Person ends a specified role by company        Low             1.213172
                     Person ends any role by company                Low             0.346620
                     Person starts a specified role by company      Low             1.733102
                     Person starts any role by company              Low             4.852686
                     Preferred Dividend                             Low             3.639515
                     Regulatory Agency Inquiries                    Low             0.173310
                     Special/Extraordinary Shareholders Meeting     Low             0.346620
                     acquisition_announcements                      Low             0.519931

                                                                                    Headline  \
Company              Connection Type                                Market Impact
BB&T Corporation     Earnings releases                              Medium         12.824957
BlackRock            Earnings releases                              Medium         12.131716
F.N.B. Corporation   Earnings releases                              Medium         13.518198
M&T Bank Corporation Annual General Meeting                         High            2.426343
                     Buyback - Change in Plan Terms                 Low             0.173310
                     Buyback Tranche Update                         Low             6.759099
                     Buyback Transaction Announcements              Low             2.079723
                     Corporate Guidance - New/Confirmed             High            1.039861
                     Discontinued Operations/Downsizings            Low             3.466205
                     Dividend Affirmations                          Low            10.225303
                     Dividend Increases                             Medium          1.039861
                     Earnings releases                              High           13.518198
                     Fixed Income Issuance Announcements by Company Low             0.866551
                     Impairments/Write Offs                         Low             3.812825
                     M&A Calls                                      Low             0.519931
                     News                                           Low             2.772964
                     Person ends a specified role by company        Low             1.213172
                     Person ends any role by company                Low             0.346620
                     Person starts a specified role by company      Low             1.733102
                     Person starts any role by company              Low             4.852686
                     Preferred Dividend                             Low             3.639515
                     Regulatory Agency Inquiries                    Low             0.173310
                     Special/Extraordinary Shareholders Meeting     Low             0.346620
                     acquisition_announcements                      Low             0.519931

                                                                                   Smart Connection
Company              Connection Type                                Market Impact
BB&T Corporation     Earnings releases                              Medium                12.824957
BlackRock            Earnings releases                              Medium                12.131716
F.N.B. Corporation   Earnings releases                              Medium                13.518198
M&T Bank Corporation Annual General Meeting                         High                   0.000000
                     Buyback - Change in Plan Terms                 Low                    0.000000
                     Buyback Tranche Update                         Low                    0.000000
                     Buyback Transaction Announcements              Low                    0.000000
                     Corporate Guidance - New/Confirmed             High                   0.000000
                     Discontinued Operations/Downsizings            Low                    0.000000
                     Dividend Affirmations                          Low                    0.000000
                     Dividend Increases                             Medium                 0.000000
                     Earnings releases                              High                   0.000000
                     Fixed Income Issuance Announcements by Company Low                    0.000000
                     Impairments/Write Offs                         Low                    0.000000
                     M&A Calls                                      Low                    0.000000
                     News                                           Low                    0.000000
                     Person ends a specified role by company        Low                    0.000000
                     Person ends any role by company                Low                    0.000000
                     Person starts a specified role by company      Low                    0.000000
                     Person starts any role by company              Low                    0.000000
                     Preferred Dividend                             Low                    0.000000
                     Regulatory Agency Inquiries                    Low                    0.000000
                     Special/Extraordinary Shareholders Meeting     Low                    0.000000
                     acquisition_announcements                      Low                    0.000000

In [124]:
df1_counts = df1.pivot_table(index=['Market Impact'],aggfunc='count')
df1_counts

               Company  Connection Type  Date  Headline  Smart Connection
Market Impact
High                98               98    98        98                 0
Low                251              251   251       251                 0
Medium             228              228   228       228               222

In [125]:
(df1_counts / len(df1)*100)

,Company,Connection Type,Date,Headline,Smart Connection
Market Impact,,,,,
High,16.984402,16.984402,16.984402,16.984402,0.00000
Low,43.500867,43.500867,43.500867,43.500867,0.00000
Medium,39.514731,39.514731,39.514731,39.514731,38.47487

In [175]:
df_co = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                    encoding='utf-8',sheetname=4,parse_dates=True)

C:\Users\zanderl\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel.py:351: UserWarning: The 'parse_dates=True' keyword of read_excel was provided without an 'index_col' keyword value.
  warn("The 'parse_dates=True' keyword of read_excel was provided"

In [176]:
df_co.head()

Empty DataFrame
Columns: [Date, Company, Smart Connection, Connection Type, Headline, Market Impact]
Index: []

In [177]:
df_co.iloc[0,1]

IndexError: single positional indexer is out-of-bounds

In [77]:
co_name = 'Cisco Systems'
df_co = df_co[df_co['Company'] != str(co_name)]
#df_co = df_co[df_co['Company'] == str(co_name)]
#df_co

In [78]:
df_co.set_index(['Connection Type','Market Impact']);

In [81]:
df_co_counts = df_co.pivot_table(index=['Market Impact','Connection Type'],aggfunc='count')
df_co_counts

Empty DataFrame
Columns: []
Index: []

In [80]:
df_co_counts.to_excel('CSCO Other Company.xlsx')

IndexError: index 0 is out of bounds for axis 0 with size 0

# Note on the below try except statement.  
You need to have the entire code block within the try except statement because it runs through that first before going to any new code. So for any code outside of the try except statement, you'll get errors telling you that certain variables are being references prior to being defined.

In [197]:
def GetSimilarCoData(sheetname):
    # Cannot use co_name as sheetname because they are different
    # co_name must be the CIQ short company name while the tabs contain the long company names
    
    #company_names_df = pd.read_excel("C:/Users/zanderl/Downloads/Analyst's Combined Watch List with CIQ IDs.xlsx",
    #                      encoding='utf-8',sheetname=2)
    
    try:
        df_company = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                              encoding='utf-8',
                              sheetname=sheetname)

        co_name = str(df_company.iloc[sheetname,1])
        df_co = df_company[df_company['Company'] == str(co_name)]
        df_co.set_index(['Connection Type','Market Impact'])
        df_co_counts = df_co.pivot_table(index=['Market Impact','Connection Type'],aggfunc='count')
        df_co_counts.to_excel(co_name+' Own Company.xlsx')
        return [co_name, df_co_counts]
    except IndexError:
        pass

In [217]:
for i in range(25,79,1):
    CoData_df = GetSimilarCoData(i)

try:
    CoData_df[0]
    CoData_df[1]
except TypeError:
    pass
#CoData_df

'Qualcomm Inc.'

                                                              Company  Date  \
Market Impact Connection Type
High          Annual General Meeting                               14    14
              Corporate Guidance - Lowered                          3     3
              Corporate Guidance - New/Confirmed                   56    56
              Corporate Guidance - Raised                          42    42
              Dividend Increases                                   26    26
              Earnings releases                                    79    79
              News                                                 41    41
Low           Analyst/Investor Day                                  4     4
              Buyback Tranche Update                               41    41
              Buyback Transaction Announcements                    11    11
              Considering Multiple Strategic Alternatives           4     4
              Discontinued Operations/Downsizings                   7     7
              Fixed Income Issuance Announcements by Company        2     2
              M&A Calls                                             4     4
              News                                                414   414
              Person ends a specified role by company               4     4
              Person ends any role by company                       3     3
              Person starts a specified role by company             2     2
              Person starts any role by company                    22    22
              Regulatory Agency Inquiries                           1     1
              acquisition_announcements                            12    12
Medium        Dividend Affirmations                                53    53
              News                                                 64    64
              Shareholder/Analyst Calls                            17    17

                                                              Headline  \
Market Impact Connection Type
High          Annual General Meeting                                14
              Corporate Guidance - Lowered                           3
              Corporate Guidance - New/Confirmed                    56
              Corporate Guidance - Raised                           42
              Dividend Increases                                    26
              Earnings releases                                     79
              News                                                  41
Low           Analyst/Investor Day                                   4
              Buyback Tranche Update                                41
              Buyback Transaction Announcements                     11
              Considering Multiple Strategic Alternatives            4
              Discontinued Operations/Downsizings                    7
              Fixed Income Issuance Announcements by Company         2
              M&A Calls                                              4
              News                                                 414
              Person ends a specified role by company                4
              Person ends any role by company                        3
              Person starts a specified role by company              2
              Person starts any role by company                     22
              Regulatory Agency Inquiries                            1
              acquisition_announcements                             12
Medium        Dividend Affirmations                                 53
              News                                                  64
              Shareholder/Analyst Calls                             17

                                                              Smart Connection
Market Impact Connection Type
High          Annual General Meeting                                         0
              Corporate Guidance - Lowered                                   0
              Corporate Guidance - New/Confirmed                             0
              Corporate Guidance - Raised                                    0
              Dividend Increases                                             0
              Earnings releases                                              0
              News                                                          18
Low           Analyst/Investor Day                                           0
              Buyback Tranche Update                                         0
              Buyback Transaction Announcements                              0
              Considering Multiple Strategic Alternatives                    0
              Discontinued Operations/Downsizings                            0
              Fixed Income Issuance Announcements by Company                 0
              M&A Calls                                                      0
              News                                                         358
              Person ends a specified role by company                        0
              Person ends any role by company                                0
              Person starts a specified role by company                      0
              Person starts any role by company                              0
              Regulatory Agency Inquiries                                    0
              acquisition_announcements                                      0
Medium        Dividend Affirmations                                          0
              News                                                          54
              Shareholder/Analyst Calls                                      0

In [220]:
def GetOtherCoData(sheetname):
    # Cannot use co_name as sheetname because they are different
    # co_name must be the CIQ short company name while the tabs contain the long company names
    
    #company_names_df = pd.read_excel("C:/Users/zanderl/Downloads/Analyst's Combined Watch List with CIQ IDs.xlsx",
    #                      encoding='utf-8',sheetname=2)
    
    try:
        df_company = pd.read_excel("C:/Users/zanderl/Documents/Data Science/Kensho Smart Connections Data/companies.xlsx",
                              encoding='utf-8',
                              sheetname=sheetname)

        co_name = str(df_company.iloc[sheetname,1])
        df_co = df_company[df_company['Company'] != str(co_name)]
        df_co.set_index(['Connection Type','Market Impact'])
        df_co_counts = df_co.pivot_table(index=['Market Impact','Connection Type'],aggfunc='count')
        df_co_counts.to_excel(co_name+' Other Company.xlsx')
        return [co_name, df_co_counts]
    except IndexError:
        pass

In [221]:
for i in range(0,79,1):
    CoData_df = GetOtherCoData(i)

try:
    CoData_df[0]
    CoData_df[1]
except TypeError:
    pass
#CoData_df

'Qualcomm Inc.'

                                            Company  Date  Headline  \
Market Impact Connection Type
High          News                               11    11        11
Low           News                              122   122       122
Medium        Corporate Guidance - Lowered       17    17        17
              Corporate Guidance - Raised        25    25        25
              Earnings releases                 237   237       237
              News                               11    11        11

                                            Smart Connection
Market Impact Connection Type
High          News                                        11
Low           News                                       122
Medium        Corporate Guidance - Lowered                17
              Corporate Guidance - Raised                 25
              Earnings releases                          237
              News                                        11